{
  "comments": [
    {
      "key": {
        "uuid": "9ab8dda7_1dc4d65d",
        "filename": "tests/unit/reporter/test_testapi.py",
        "patchSetId": 1
      },
      "lineNbr": 53,
      "author": {
        "id": 6435
      },
      "writtenOn": "2017-04-16T07:08:27Z",
      "side": 1,
      "message": "Just a small doubt. \n\nIs it accepted to actually interact with the Testapi server for testing not found error?",
      "revId": "0d165d6531235d7099ba3e712006704401e0ec1f",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}